apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-shop-frontend-deployment
  labels:
    app: flask-shop-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-shop-frontend
  template:
    metadata:
      labels:
        app: flask-shop-frontend
    spec:
      containers:
      - name: flask-shop-frontend
        image: <your_dockerhub_username>/<frontend_image_name>:<frontend_image_version>
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: flask-shop-frontend-service
spec:
  selector:
    app: flask-shop-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
