apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-shop-frontend
  labels:
    app: flask-shop-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-shop-frontend
  template:
    metadata:
      labels:
        app: flask-shop-frontend
    spec:
      containers:
        - name: flask-shop-backend
          image: jmlero/simplefrontend-python:0.1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: flask-shop-frontend
spec:
  selector:
    app: flask-shop-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
