apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-shop-backend
  labels:
    app: flask-shop-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-shop-backend
  template:
    metadata:
      labels:
        app: flask-shop-backend
    spec:
      containers:
        - name: flask-shop-backend
          image: jmlero/simplebackend-python:0.1
          ports:
            - containerPort: 5000
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: flask-shop-backend
spec:
  selector:
    app: flask-shop-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
