apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-shop-app-deployment
  labels:
    app: flask-shop-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-shop-app
  template:
    metadata:
      labels:
        app: flask-shop-app
    spec:
      containers:
      - name: flask-shop-app
        image: 
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-shop-app-service
spec:
  selector:
    app: flask-shop-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
