apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-shop-backend
  labels:
    app: flask-shop-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-shop-backend
  template:
    metadata:
      labels:
        app: flask-shop-backend
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      containers:
        - name: flask-shop-backend
          image: jmlero/simplebackend-python:0.1
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          env: # Add these environment variables
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "otel-collector-collector:4318"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=flask-shop-backend"
            - name: OTEL_COLLECTOR_NAME
              value: "flask-shop-backend"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-shop-backend
spec:
  selector:
    app: flask-shop-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
