name: Build and Push Docker images

on:
  push:
    branches:
      - main # or the name of your default branch if not 'main'

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./simplebackend-python
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/simplebackend-python:latest

  frontend-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./simplefrontend-python
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/simplefrontend-python:latest
